version: 2
updates:
  - package-ecosystem: npm
    directory: "/app"
    schedule:
      interval: daily
      time: "07:00"
      timezone: Australia/Perth
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
      timezone: Australia/Perth
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
      timezone: Australia/Perth
    open-pull-requests-limit: 10
