[tool.poetry]
name = "media"
version = "0.1.0"
description = ""
authors = ["Elliana May <me@mause.me>"]
license = "MIT"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
skip_string_normalization=true

[tool.isort]
profile = "black"

[tool.poetry.dependencies]
python = "^3.8"
flask = "*"
requests = "*"
sqlalchemy = "*"
sqlalchemy-repr = "*"
flask-sqlalchemy = "*"
aiohttp = "*"
requests-toolbelt = "*"
backoff = "*"
gunicorn = {extras = ["gevent"], version = "*"}
psycopg2-binary = "*"
dataclasses-json = "*"
flask-user = "*"
flask-admin = "*"
flask-jsontools = "*"
sentry-sdk = {extras = ["flask"], version = "*"}
alembic = "*"
plexapi = "*"
flask-cors = "*"
flask-restx = {git = "https://github.com/python-restx/flask-restx"}
werkzeug = "==1.*"
apispec = "*"
flask-login = "==0.5.0"
fuzzywuzzy = {extras = ["speedup"], version = "*"}
cachetools = "*"
lxml = "*"
bs4 = "*"
flask-socketio = "*"
timber = "*"
eventlet = "*"
email-validator = "*"
mause-rpc = "*"
py-healthcheck = "*"
cffi = "*"
fastapi = "*"
python-multipart = "*"
jwkaas = "*"
aniso8601 = "*"

[tool.poetry.dev-dependencies]
ipdb = "*"
pytest = "*"
pdbpp = "*"
responses = "*"
lxml = "*"
selenium = "*"
pytest-html = "*"
pytest-flask = "*"
pytest-selenium = "*"
webdriver-manager = "*"
pre-commit = "*"
sqlalchemy-stubs = "*"
snapshottest = "*"
black = "*"
flake8 = "*"
mypy = "*"
