
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.8.0-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            sudo pip3 install pipenv
            pipenv sync --dev
      - save_cache:
          paths:
            - '{{ pipenv --env }}'
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: Mypy
          command: |
            pipenv run mypy rarbg_local
      - run:
          name: Run Tests
          environment: {}
          command: |
            mkdir screenshots
            . $(pipenv --venv)/Scripts/activate
            py.test . -v --junitxml=test-reports/junit/junit.xml
      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: report.html
          destination: report.html
