"""Add tmdb_id column

Revision ID: 01602e6e9637
Revises: 050b415e6bc9
Create Date: 2020-01-09 07:38:13.146945

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '01602e6e9637'
down_revision = '050b415e6bc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download', sa.Column('tmdb_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('download', 'tmdb_id')
    # ### end Alembic commands ###
