"""Initial database schema

Revision ID: 050b415e6bc9
Revises: baseline
Create Date: 2020-01-08 18:23:24.931828

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '050b415e6bc9'
down_revision = 'baseline'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'episode_details',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('show_title', sa.String(), nullable=False),
        sa.Column('season', sa.Integer(), nullable=False),
        sa.Column('episode', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'movie_details',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
        sa.Column('username', sa.String(length=255, collation='en_AU'), nullable=False),
        sa.Column('password', sa.String(length=255), server_default='', nullable=False),
        sa.Column(
            'first_name',
            sa.String(length=100, collation='en_AU'),
            server_default='',
            nullable=False,
        ),
        sa.Column(
            'last_name',
            sa.String(length=100, collation='en_AU'),
            server_default='',
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username'),
    )
    op.create_table(
        'download',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('transmission_id', sa.String(), nullable=False),
        sa.Column('imdb_id', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=True),
        sa.Column('movie_id', sa.Integer(), nullable=True),
        sa.Column('episode_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['episode_id'], ['episode_details.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['movie_id'], ['movie_details.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'user_roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('download')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('movie_details')
    op.drop_table('episode_details')
    # ### end Alembic commands ###
