"""empty message

Revision ID: 27161b23fd97
Revises: f5bb1143a337
Create Date: 2020-02-19 18:44:13.960531

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '27161b23fd97'
down_revision = 'f5bb1143a337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitor')
    # ### end Alembic commands ###
