"""empty message

Revision ID: 2abd0ee3433d
Revises: f5bb1143a337
Create Date: 2020-02-21 08:26:21.571083

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '2abd0ee3433d'
down_revision = 'f5bb1143a337'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    '''
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    if 'monitor' in tables:
        op.drop_table('monitor')
    '''

    op.create_table(
        'monitor',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tmdb_id', sa.Integer(), nullable=True),
        sa.Column('added_by_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['added_by_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitor')
    # ### end Alembic commands ###
