"""Add email column

Revision ID: 42d9d38a0eb2
Revises: a5a64168f6c1
Create Date: 2020-08-18 21:36:01.602787

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '42d9d38a0eb2'
down_revision = 'a5a64168f6c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as context:
        context.add_column(
            sa.Column(
                'email',
                sa.String(length=255, collation='en_AU'),
                nullable=True,
            )
        )
        context.create_unique_constraint('users_unique_email', ['email'])
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_unique_email', 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
