"""empty message

Revision ID: 5931d87627b6
Revises: 42d9d38a0eb2
Create Date: 2025-05-22 11:22:10.681176

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '5931d87627b6'
down_revision = '42d9d38a0eb2'
branch_labels = None
depends_on = None

constraint_name = 'fk_download_added_by_id_users_id'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download', schema=None) as batch_op:
        batch_op.create_foreign_key(constraint_name, 'users', ['added_by_id'], ['id'])

    with op.batch_alter_table('monitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitor', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('download', schema=None) as batch_op:
        batch_op.drop_constraint(constraint_name, type_='foreignkey')

    # ### end Alembic commands ###
