"""mark columns as not nullable as required

Revision ID: 783d52a969dd
Revises: 5931d87627b6
Create Date: 2025-07-03 01:03:30.730140

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '783d52a969dd'
down_revision: str | Sequence[str] | None = '5931d87627b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download', schema=None) as batch_op:
        batch_op.alter_column('type', existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column('title', existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column('added_by_id', existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table('monitor', schema=None) as batch_op:
        batch_op.alter_column('tmdb_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('added_by_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('status', existing_type=sa.BOOLEAN(), nullable=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column(
            'name', existing_type=sa.VARCHAR(length=50), nullable=False
        )

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('role_id', existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.alter_column('role_id', existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column('user_id', existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column(
            'name', existing_type=sa.VARCHAR(length=50), nullable=True
        )

    with op.batch_alter_table('monitor', schema=None) as batch_op:
        batch_op.alter_column('status', existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column('added_by_id', existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column('tmdb_id', existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table('download', schema=None) as batch_op:
        batch_op.alter_column('added_by_id', existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column('title', existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column('type', existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###
