"""empty message

Revision ID: a5a64168f6c1
Revises: 2abd0ee3433d
Create Date: 2020-03-08 18:01:55.431768

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a5a64168f6c1'
down_revision = '2abd0ee3433d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitor', sa.Column('type', sa.Enum('MOVIE', 'EPISODE', name='mediatype'), server_default='MOVIE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitor', 'type')
    # ### end Alembic commands ###
