"""empty message

Revision ID: f5bb1143a337
Revises: 3e86cca42fcb
Create Date: 2020-01-18 14:29:06.006593

"""

import sqlalchemy as sa

from alembic import op
from common import get_driver

# revision identifiers, used by Alembic.
revision = 'f5bb1143a337'
down_revision = '3e86cca42fcb'
branch_labels = None
depends_on = None

constraint_name = 'fk_download_added_by_id_users_id'


def upgrade() -> None:
    sqlite = get_driver() == 'sqlite'

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download', sa.Column('added_by_id', sa.Integer(), nullable=True))
    if not sqlite:
        op.create_foreign_key(
            constraint_name, 'download', 'users', ['added_by_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(constraint_name, 'download', type_='foreignkey')
    op.drop_column('download', 'added_by_id')
    # ### end Alembic commands ###
