"""empty message

Revision ID: f5bb1143a337
Revises: 3e86cca42fcb
Create Date: 2020-01-18 14:29:06.006593

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'f5bb1143a337'
down_revision = '3e86cca42fcb'
branch_labels = None
depends_on = None

constraint_name = 'fk_download_added_by_id_users_id'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download') as batch_op:
        batch_op.add_column(sa.Column('added_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(constraint_name, 'users', ['added_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download') as batch_op:
        batch_op.drop_constraint(constraint_name, type_='foreignkey')
        batch_op.drop_column('added_by_id')
    # ### end Alembic commands ###
