yarnPath: .yarn/releases/yarn-2.1.1.cjs

packageExtensions:
  "@sentry/hub@*":
    dependencies:
      "@types/node": "*"
  "@sentry/react@*":
    dependencies:
      "@types/react": "*"
  "react-contextmenu@*":
    dependencies:
      "@types/react": "*"
  "react-collapsible@*":
    dependencies:
      "@types/react": "*"
  "react-loading@*":
    dependencies:
      "@types/react": "*"
  "swr@*":
    dependencies:
      "@types/react": "*"
  "@auth0/auth0-react@*":
    dependencies:
      "@types/react": "*"
  "@fortawesome/react-fontawesome@*":
    dependencies:
      "@types/react": "*"
  "react-error-boundary@*":
    dependencies:
      "@types/react": "*"
  "use-socketio@*":
    dependencies:
      "@types/socket.io-client": "*"
      "@types/react": "*"
  "@testing-library/react@*":
    dependencies:
      "@types/react-dom": "*"
  "react-scripts@*":
    dependencies:
      "@types/node": "*"
      "@types/react": "*"
      "@types/react-dom": "*"
