packageExtensions:
  "@auth0/auth0-react@*":
    dependencies:
      "@types/react": "*"
  "@fortawesome/react-fontawesome@*":
    dependencies:
      "@types/react": "*"
  "@sentry/hub@*":
    dependencies:
      "@types/node": "*"
  "@sentry/react@*":
    dependencies:
      "@types/react": "*"
  "@testing-library/react@*":
    dependencies:
      "@types/react-dom": "*"
  react-collapsible@*:
    dependencies:
      "@types/react": "*"
  react-contextmenu@*:
    dependencies:
      "@types/react": "*"
  react-error-boundary@*:
    dependencies:
      "@types/react": "*"
  react-loading@*:
    dependencies:
      "@types/react": "*"
  react-scripts@*:
    dependencies:
      "@types/node": "*"
      "@types/react": "*"
      "@types/react-dom": "*"
  swr@*:
    dependencies:
      "@types/react": "*"
  use-socketio@*:
    dependencies:
      "@types/react": "*"
      "@types/socket.io-client": "*"

yarnPath: .yarn/releases/yarn-2.3.3.cjs
