from typing import Any

class TTLCache:
    def __init__(self, maxsize=None, ttl=None): ...
    def __getitem__(self, name) -> Any: ...
    def __contains__(self, name) -> bool: ...
    def __setitem__(self, name, value: Any): ...

class LRUCache:
    def __init__(self, maxsize=None): ...
    def __getitem__(self, name) -> Any: ...
    def __contains__(self, name) -> bool: ...
    def __setitem__(self, name, value: Any): ...
