name: Client

on: push

jobs:
  generate_client:
    name: Generate client
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-java@v1
      with:
              java-version: 8
    - run: npx @openapitools/openapi-generator-cli generate -i https://media.mause.me/openapi.json -g python -o client --skip-validate-spec
    - uses: actions/upload-artifact@v4
      with:
        name: client
        path: client
