name: Client

on: push

jobs:
  generate_client:
    name: Check client
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v5
    - run: corepack enable
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
    - uses: nickcharlton/diff-check@main
      with:
        command: |
          cd app && yarn && yarn generate:static
