name: Client

on: push

jobs:
  generate_client:
    name: Generate client
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - run: corepack enable
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - uses: nickcharlton/diff-check@main
      with:
        command: |
          npx openapi-typescript rarbg_local/tests/snapshots/test_integration/test_openapi/openapi.json -o app/src/schema.ts
          cd app && yarn && yarn prettier --write src/schema.ts
