name: Client

on: push

jobs:
  generate_client:
    name: Generate client
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-java@v1
      with:
              java-version: 8
    - run: npm install -g openapi-generator
    - run: openapi-generator generate -i modules/openapi-generator/src/test/resources/2_0/petstore.json -g perl --git-user-id "wing328" --git-repo-id "petstore-perl" --release-note "GitHub integration demo" -o /var/tmp/perl/petstore
