on:
  push:
    branches:
      - 'dependabot/npm_and_yarn/*'

jobs:
  rebuild:
    name: Rebuild
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          python3 .github/workflows/run_yarn.py

    #  - run: |
    #      git config user.name github-actions
    #      git config user.email github-actions@github.com
    #      git add .
    #      git commit -m "generated"
    #      git push
