# .github/workflows/lint-migrations.yml
name: Lint Migrations

on: pull_request

jobs:
  lint_migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install uv
        run: |
          python -m pip install --upgrade uv
      - name: Install dependencies
        run: |
          uv sync --dev
      - name: Generate sql
        run: |
          uv run alembic upgrade head --sql > report.sql
      - uses: sbdchd/squawk-action@v1
        with:
          pattern: report.sql
