name: Node.js CI

on: [push]

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    # set default working directory
    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v5
      - run: corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn
      - run: yarn build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      # hack from https://christopher.xyz/2023/04/04/github-actions-problem-matchers.html
      - run: yarn tsc | awk -v prefix="$PWD" '{print prefix "/" $0}'
      - run: yarn test
      - run: yarn oxlint
