name: Node.js CI

on: [push]

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    # set default working directory
    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn
      - run: yarn build
      - run: yarn tsc
      - run: yarn test
