name: Node.js CI

on: [push]

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - run: corepack enable
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
        working-directory: app
      - run: yarn build
        working-directory: app
        env:
          CI: true
      - run: yarn test --ci --runInBand
        working-directory: app
        env:
          CI: true
