name: Python application

on: [push]

jobs:
  build_backend:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.12

    env:
      UV_PYTHON: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: 'uv.lock'
      - name: Install dependencies
        run: |
          uv sync --dev --locked
      - name: Run mypy
        uses: liskin/gh-problem-matcher-wrap@v3
        with:
          linters: mypy
          run: uv run mypy --show-column-numbers rarbg_local
      - run: uv run alembic upgrade head --sql
      - name: Test with pytest
        run: |
          uv run pytest -vv
        env:
          CLOUDAMQP_URL: 'https://hello'
          TMDB_API_KEY: word
          TMDB_READ_ACCESS_TOKEN: word
          PYTEST_ADDOPTS: '--color=yes'
      - name: Archive test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report-${{ matrix.python-version }}.html
          path: report.html

  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
      - run: yarn
        working-directory: app/
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
