name: Python application

on: [push]

jobs:
  build_backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - 3.9

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pipenv virtualenv
        id: cache-pipenv
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ matrix.python-version }}-${{ hashFiles('**/Pipfile.lock') }}-2
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv sync --dev
      - name: Run mypy
        if: false
        run: |
          pipenv run mypy rarbg_local
      - run: pipenv run alembic upgrade head --sql
      - name: Test with pytest
        run: |
          pipenv run pytest -vv
        env:
          CLOUDAMQP_URL: "https://hello"
          TMDB_API_KEY: word
          TMDB_READ_ACCESS_TOKEN: word
      - name: Archive test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report.html
          path: report.html
