name: Python application

on: [push]

permissions:
  contents: read

jobs:
  build_backend:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.13
          # - 3.14

    env:
      UV_PYTHON: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: "latest"
      - name: Install dependencies
        run: |
          uv sync --dev --locked
      - name: Run mypy
        uses: liskin/gh-problem-matcher-wrap@d31bb388d13cf879e93f878cb2550299f0afb460 # v4
        with:
          linters: mypy
          run: uv run mypy --show-column-numbers rarbg_local
      - run: uv run alembic upgrade head --sql
      - name: Test with pytest
        uses: liskin/gh-problem-matcher-wrap@d31bb388d13cf879e93f878cb2550299f0afb460 # v4
        with:
          linters: pytest
          run: uv run pytest -v
        env:
          CLOUDAMQP_URL: "https://hello"
          TMDB_API_KEY: word
          TMDB_READ_ACCESS_TOKEN: word
          PYTEST_ADDOPTS: "--color=yes"
      - name: Archive test report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: always()
        with:
          name: report-${{ matrix.python-version }}.html
          path: report.html

  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
      - run: corepack enable
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: "22"
          cache: "yarn"
      - run: yarn
        working-directory: app/
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
